# ewelink 4ch relay
# 4CH WIFI Relay Switch

esphome:
  name: control-bombas-2

esp8266:
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  reboot_timeout: 60s
logger:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Boton 1"
    on_release:
        - switch.toogle: relay_turbina
  - platform: gpio
    pin:
      number: GPIO9
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Boton 2"
    on_release:
        - switch.toogle: relay_rotofiltro
  - platform: gpio
    pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Boton 3"
    on_release:
        - switch.toogle: relay_bombra_limpieza
  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Boton 4"
    on_release:
        - switch.toogle: relay_bomba_manguera    
  - platform: status
    name: "Control Motores"

switch:
  - platform: gpio
    name: "Relay 1 Turbina"
    pin: GPIO12
    id: relay_turbina
  - platform: gpio
    name: "Relay 2 Rotofiltro"
    pin: GPIO5
    id: relay_rotofiltro
  - platform: gpio
    name: "Relay 3 Bomba Limpieza"
    pin: GPIO4
    id: relay_bombra_limpieza
  - platform: gpio
    name: "Relay 4 Bomba Manguera"
    pin: GPIO15
    id: relay_bomba_manguera

output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: red_led
    pin: GPIO13
    inverted: true

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "LED rojo"
    output: red_led
